### PR TITLE
Support for laravel 11

### PR DESCRIPTION
**Pull request by rizkyseptiawan**

### CODE REVIEW

**Comment by reliq** [comment]
Thank you @rizkyseptiawan

**Comment by rizkyseptiawan** [comment]
Youre welcome @reliq . I have tried to install it in my project, but there are still problems with the reliqarts/laravel-common dependency. Is it necessary to also update the composer version of the dependency to version v8.0?

**Comment by reliq** [comment]
@rizkyseptiawan please post the error and your Laravel version as a new issue [here](https://github.com/reliqarts/laravel-auto-translator/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=) and I will take a look. 

--- 

edit: I see what might be the problem. I have fixed it with this [PR](https://github.com/reliqarts/laravel-auto-translator/pull/2). If you see another problem feel free to reach out.

**Comment by rizkyseptiawan** [comment]
Thanks a lot @reliq

**Pull request merged**
